### ISSUE TITLE
RCov does not work with Ruby 2.0. Please use simplecov.

### ISSUE THREAD

**Issue by louiseyang** [mokemokechicken/CrashMonkey#5]
```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
creating Makefile

make "DESTDIR="
compiling 1.8/callsite.c
1.8/callsite.c:2:10: fatal error: 'env.h' file not found
#include <env.h>
         ^
1 error generated.
make: *** [callsite.o] Error 1


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/rcov-1.0.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/rcov-1.0.0/ext/rcovrt/gem_make.out
An error occurred while installing rcov (1.0.0), and Bundler cannot continue.
Make sure that `gem install rcov -v '1.0.0'` succeeds before bundling.
```

line16 in Gemfile should be if RUBY_VERSION > "1.9"
